-- ============================================================
--  FASE 4 — PEDIDOS
--  Corre esto en Supabase > SQL Editor (una sola vez).
--  Guarda las ventas, descuenta stock y calcula precios de forma
--  segura en el servidor. Los pedidos son PRIVADOS (solo admin).
-- ============================================================

-- ---------- 1) Tabla de pedidos ----------
create table if not exists pedidos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,
  cliente_nombre text not null,
  cliente_telefono text not null,
  cliente_direccion text,
  notas text,
  total numeric not null default 0,
  estado text not null default 'pendiente',
  created_at timestamptz default now()
);

-- ---------- 2) Items de cada pedido ----------
-- Guarda una "foto" del nombre y precio al momento de la compra,
-- para que el pedido no cambie aunque luego edites el producto.
create table if not exists pedido_items (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references pedidos(id) on delete cascade,
  producto_id uuid references productos(id) on delete set null,
  nombre text not null,
  precio numeric not null,
  cantidad int not null
);
create index if not exists pedido_items_pedido_idx on pedido_items (pedido_id);

-- ---------- 3) Seguridad: pedidos privados (solo admin) ----------
alter table pedidos enable row level security;
alter table pedido_items enable row level security;

drop policy if exists "pedidos admin select" on pedidos;
drop policy if exists "pedidos admin update" on pedidos;
drop policy if exists "pedidos admin delete" on pedidos;
create policy "pedidos admin select" on pedidos
  for select to authenticated using (true);
create policy "pedidos admin update" on pedidos
  for update to authenticated using (true) with check (true);
create policy "pedidos admin delete" on pedidos
  for delete to authenticated using (true);

drop policy if exists "pedido_items admin select" on pedido_items;
create policy "pedido_items admin select" on pedido_items
  for select to authenticated using (true);

-- ---------- 4) Función segura para crear el pedido ----------
-- Valida stock, calcula el precio (con descuento) en el servidor,
-- inserta el pedido + items y descuenta el stock, todo junto.
create or replace function crear_pedido(
  p_nombre text,
  p_telefono text,
  p_direccion text,
  p_notas text,
  p_items jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido_id uuid;
  v_numero bigint;
  v_total numeric := 0;
  v_item jsonb;
  v_prod productos%rowtype;
  v_cant int;
  v_precio numeric;
begin
  if p_nombre is null or length(trim(p_nombre)) = 0 then
    raise exception 'El nombre es obligatorio';
  end if;
  if p_telefono is null or length(trim(p_telefono)) = 0 then
    raise exception 'El teléfono es obligatorio';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'El carrito está vacío';
  end if;

  insert into pedidos (
    cliente_nombre, cliente_telefono, cliente_direccion, notas, total, estado
  ) values (
    trim(p_nombre),
    trim(p_telefono),
    nullif(trim(coalesce(p_direccion, '')), ''),
    nullif(trim(coalesce(p_notas, '')), ''),
    0,
    'pendiente'
  ) returning id, numero into v_pedido_id, v_numero;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_cant := (v_item->>'cantidad')::int;
    if v_cant is null or v_cant < 1 then
      raise exception 'Cantidad inválida';
    end if;

    -- bloquea la fila del producto para evitar sobreventa
    select * into v_prod from productos
      where id = (v_item->>'producto_id')::uuid for update;
    if not found then
      raise exception 'Uno de los productos ya no está disponible';
    end if;
    if v_prod.stock < v_cant then
      raise exception 'Sin stock suficiente de %', v_prod.nombre;
    end if;

    -- precio con descuento, calculado en el servidor (no se confía en el cliente)
    v_precio := round(v_prod.precio * (1 - coalesce(v_prod.descuento, 0)::numeric / 100));

    insert into pedido_items (pedido_id, producto_id, nombre, precio, cantidad)
    values (v_pedido_id, v_prod.id, v_prod.nombre, v_precio, v_cant);

    update productos set stock = stock - v_cant where id = v_prod.id;

    v_total := v_total + v_precio * v_cant;
  end loop;

  update pedidos set total = v_total where id = v_pedido_id;

  return jsonb_build_object('id', v_pedido_id, 'numero', v_numero, 'total', v_total);
end;
$$;

grant execute on function crear_pedido(text, text, text, text, jsonb) to anon, authenticated;
